# Generated by Django 5.0.3 on 2024-05-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('BS-CS', 'BS in Computer Science'), ('BS-DS', 'BS in Data Science'), ('BS-IT', 'BS in Information Technology'), ('BS-IS', 'BS in Information Systems')], max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
